# -*- coding: utf-8 -*-
"""make_plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfmmZw8VbUAik3UI7dWv3TMCFvS4WB5w
"""

import matplotlib.pyplot as plt
def load_scores(path, m):
  g_is_fid=[]
  imh_is_fid=[]
  for s in ['5','10','15','20','25','30']:
    arr=torch.load('%s/_score_g_%s' % (path+'is_fid'+m, s))
    g_is_fid.append(arr[0])
    imh_is_fid.append(arr[1])
  g_is=[]
  g_is_scat=[]
  imh_is=[]
  imh_is_scat=[]
  g_fid=[]
  g_fid_scat=[]
  imh_fid=[]
  imh_fid_scat=[]
  for i in range(6):
    for j in range(5):
      g_is_scat.append(g_is_fid[i][j][0])
      g_fid_scat.append(np.mean(g_is_fid[i][j][1]))
      imh_is_scat.append(imh_is_fid[i][j][0])
      imh_fid_scat.append(np.mean(imh_is_fid[i][j][1]))
    g_is_scat=tuple(g_is_scat)
    g_fid_scat=tuple(g_fid_scat)
    imh_is_scat=tuple(imh_is_scat)
    imh_fid_scat=tuple(imh_fid_scat)
    g_is.append(g_is_scat)
    g_fid.append(g_fid_scat)
    imh_is.append(imh_is_scat)
    imh_fid.append(imh_fid_scat)
  
    g_is_scat=[]
    imh_is_scat=[]
    g_fid_scat=[]
    imh_fid_scat=[]
    g_is=np.array(g_is)
  imh_is=np.array(imh_is)
  g_fid=np.array(g_fid)
  imh_fid=np.array(imh_fid)

def make_plots():
  fig = plt.figure(figsize=(20,20))
  font = {
          'weight' : 'bold',
          'size'   : 22}

  matplotlib.rc('font', **font)
  ax1 = fig.add_subplot(111)
  ax1.scatter( [5,10,15,20,25,30],g_is[:,0], s=10, c='b', marker="s", label='original generator')
  ax1.scatter([5,10,15,20,25,30],g_is[:,1], s=10, c='b', marker="s")
  ax1.scatter([5,10,15,20,25,30],g_is[:,2], s=10, c='b', marker="s")
  ax1.scatter([5,10,15,20,25,30],g_is[:,3], s=10, c='b', marker="s")
  ax1.scatter([5,10,15,20,25,30],g_is[:,4], s=10, c='b', marker="s")

  ax1.scatter( [5,10,15,20,25,30],imh_is[:,0], s=10, c='r', marker="s", label='IMH sampled')
  ax1.scatter( [5,10,15,20,25,30],imh_is[:,1], s=10, c='r', marker="s")
  ax1.scatter( [5,10,15,20,25,30],imh_is[:,2], s=10, c='r', marker="s")
  ax1.scatter( [5,10,15,20,25,30],imh_is[:,3], s=10, c='r', marker="s")
  ax1.scatter( [5,10,15,20,25,30],imh_is[:,4], s=10, c='r', marker="s")

  ax1.plot( [5,10,15,20,25,30],np.mean(imh_is[:],axis=1), c='r', marker="s")
  ax1.plot( [5,10,15,20,25,30],np.mean(g_is[:],axis=1), c='b', marker="s")
  ax1.grid(color='black', linestyle='-', linewidth=0.5)

  plt.xlabel('Number of training epochs')

  plt.title('IS')
  plt.legend(loc='upper left');
  plt.savefig('IS_M')

  fig = plt.figure(figsize=(20,20))

  font = {'family' : 'normal',
          'size'   : 22}

  matplotlib.rc('font', **font)
  ax1 = fig.add_subplot(111)
  ax1.scatter( [5,10,15,20,25,30],g_fid[:,0], s=10, c='b', marker="s", label='original generator')
  ax1.scatter([5,10,15,20,25,30],g_fid[:,1], s=10, c='b', marker="s")
  ax1.scatter([5,10,15,20,25,30],g_fid[:,2], s=10, c='b', marker="s")
  ax1.scatter([5,10,15,20,25,30],g_fid[:,3], s=10, c='b', marker="s")
  ax1.scatter([5,10,15,20,25,30],g_fid[:,4], s=10, c='b', marker="s")

  ax1.scatter( [5,10,15,20,25,30],imh_fid[:,0], s=10, c='r', marker="s", label='IMH sampled')
  ax1.scatter( [5,10,15,20,25,30],imh_fid[:,1], s=10, c='r', marker="s")
  ax1.scatter( [5,10,15,20,25,30],imh_fid[:,2], s=10, c='r', marker="s")
  ax1.scatter( [5,10,15,20,25,30],imh_fid[:,3], s=10, c='r', marker="s")
  ax1.scatter( [5,10,15,20,25,30],imh_fid[:,4], s=10, c='r', marker="s")

  ax1.plot( [5,10,15,20,25,30],np.mean(imh_fid[:],axis=1), c='r', marker="s")
  ax1.plot( [5,10,15,20,25,30],np.mean(g_fid[:],axis=1), c='b', marker="s")
  ax1.grid(color='black', linestyle='-', linewidth=0.5)

  plt.xlabel('Number of training epochs')

  plt.title('FID')
  plt.legend(loc='upper left');
  plt.savefig('FID_M')